version: '3.6'
services:
   app:
    container_name: blog_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/blog_app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000