version: '3.6'
services:
  app:
    container_name: blog_app
    restart: always
    build:
      context: .
      dockerfile: ./docker/blog_app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
      - POSTGRES_HOST=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  bot:
    container_name: tg_bot
    build:
      context: .
      dockerfile: ./docker/tg_bot/Dockerfile
    command: python main.py
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  db:
    image: postgres:13
    container_name: blog_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
